<?= $this->doctype() ?>

<html lang="en">
<head>
  <meta charset="utf-8">
    <?= $this->headTitle('Hello World!')->setSeparator(' :: ')
        ->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

  <!-- Le styles -->
    <?= $this->headLink(['rel'  => 'shortcut icon',
                         'type' => 'image/vnd.microsoft.icon',
                         'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

  <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<div class="container">
  <div class="row">
    <!-- Page header -->
    <div class="col-md-4">
      <div class="app-caption">Hello World!</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- Navigation bar -->
      <nav class="navbar navbar-default" role="navigation">
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li class="active">
              <a href="<?= $this->url('home') ?>">Home</a>
            </li>
            <li>
              <a href="<?= $this->url('application', ['action'=>'downloads']) ?>">
                Downloads
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Support <b class="caret"></b>
                <ul class="dropdown-menu">
                  <li>
                    <a href="<?= $this->url('doc', ['page'=>'contents']) ?>">
                      Documentation
                    </a>
                  </li>
                  <li>
                    <a href="">
                      Help
                    </a>
                  </li>
                </ul>
              </a>
            </li>
            <li>
              <a href="<?= $this->url('about') ?>">About</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- Breadcrumbs -->
      <ol class="breadcrumb">
        <li class="active">Home</li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- Page content placeholder -->
        <?= $this->content; ?>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <hr>
      <p>&copy; 2005 - <?= date('Y') ?> by Your Company. All rights
        reserved.</p>
    </div>
  </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
