<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>
<div class="col-lg-9">
  <h1>Welcome to the CT.net Admin Control Panel</h1>
  <p>All of the functionality of the old CT.net is available here (or will be soon);
    you'll find that many of the menu items to your left have drop-down menus below
    them, and that's where you'll find the various functions that you're used to
    seeing in a long, unbroken list.</p>
  <p>Please let me know if you have any questions, or if you can't find something
    you think should be here, or if you have any suggestions for improvements.</p>
</div>


